WITH cte AS (
	SELECT id, ip, 
    CAST(SUBSTRING_INDEX(ip, '.', 1) AS SIGNED) AS part1, 
	CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(ip, '.', 2), '.', -1) AS SIGNED) AS part2,
	CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(ip, '.', 3), '.', -1) AS SIGNED) AS part3,
	CAST(SUBSTRING_INDEX(ip, '.', -1) AS SIGNED) AS part4
	FROM ips
	WHERE LENGTH(ip) - LENGTH(REPLACE(ip, '.', '')) = 3 
)
SELECT id, ip
FROM cte
WHERE part1 BETWEEN 0 AND 255 AND 
part2 BETWEEN 0 AND 255 AND 
part3 BETWEEN 0 AND 255 AND
part4 BETWEEN 0 AND 255 AND
(part3 BETWEEN 10 AND 99 OR part4 BETWEEN 10 AND 99)
ORDER BY id;